bit.exe: driver3.o set.o bitarray.o
	g++ driver3.o set.o bitarray.o -o bit.exe
	
driver3.o:
	g++ -c driver3.cpp -o driver3.o
	
set.o:
	g++ -c set.cpp -o set.o

bitarray.o:
	g++ -c bitarray.cpp -o bitarray.o

clean:
	rm *.o bit.exe
